### ISSUE TITLE
Waiting for the release of openserver.

### ISSUE THREAD

**Issue by QiangZhangCV** [openlinyou/openserver#1]
Great work for the easy-use C++ tools. Looking forward to the release of openserver. Thanks for your contribution!

**Comment by openlinyou** [comment]
I have been in this business for more than ten years, but I was finally eliminated by the society, and eating became a problem. It can only be said that this project came out too late. If it was ten years ago, there might have been a wave of enthusiasm, and we would continue to work on it. This item will not be updated anymore. end.
